name = "GhostStamp"
uuid = "3bf57ef4-1f3b-437b-a562-773678724159"
authors = ["Akio TOMIYA <akio.tomiya@hotmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
